"useClient"


import Arrengements from "./homepage/sections/Arrengements";
import Banner from "./homepage/sections/Banner";
import PopularCourses from "./homepage/sections/PopularCourses";
import Discussions from "./homepage/sections/Discussions";
import { Testimonials } from "./homepage/sections/Testimonials";
import Slider from "@/components/slider";
import VideoSlider from "./homepage/sections/VideoSlider";


export const metadata = {
  title: "An-Nahda Academy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};


export default function Home() {
  return (
    <div>
      <div className="absolute mt-32">
        <Slider />
      </div>
      <div className="mx-5 lg:mx-0">
        <div className="space-y-48 max-w-7xl mx-auto mb-20 ">
          <Banner />
          <Arrengements />
          <PopularCourses />

          <Testimonials />
        </div>
        <VideoSlider />
      </div>
    </div>
  );
}
