import "@/app/globals.css";
import clsx from "clsx";
import { Providers } from "./providers";
import { Hind_Siliguri } from "next/font/google";
import { Metadata } from "next";
import { ClientNavigation } from "@/components/client-navigation";
import { ClientFooter } from "@/components/client-footer";

const hindSiliguri = Hind_Siliguri({
  subsets: ['latin', 'bengali'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-hind-siliguri',
  preload: true,
});

export const metadata: Metadata = {
  title: "An-Nahda Academy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={hindSiliguri.variable}>
      <head />
      <body
        className={clsx(
          "min-h-screen bg-background antialiased font-sans overflow-x-hidden",
          hindSiliguri.className
        )}
      >
        <Providers>
          <div className="relative flex flex-col min-h-screen">
            <div className="relative flex flex-col bg-white">
              <ClientNavigation />
              <main className="flex-grow">
                {children}
              </main>
              <div className="bg-gradient-to-r from-purple-950 via-sky-950 to-indigo-950">
                <ClientFooter />
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}

// Light mode gradient only
//bg-gradient-to-tr from-sky-500 via-indigo-500 to-purple-500